### ISSUE TITLE
Easier way to make hover features [Feature]

### ISSUE THREAD

**Issue by Agaloth** [Hexaoxide/Carbon#101]
### Proposed Feature Description:
A feature in the config like on deluxechat with that format:

     channel_tooltip:
     - '&7%player_name% &bis a Member'
     prefix_tooltip:
     - '&7%player_name% &bis a Member'
     name_tooltip:
     - ''
     suffix_tooltip:
     - ''
     channel_click_command: '
     prefix_click_command: '/ranks
     name_click_command: '/msg %player_name% 
     suffix_click_command: '

**Comment by underscore11code** [comment]
As Carbon by default uses minimessage to format everything, you already have access to hover/click events via that.

**Comment by Draycia** [comment]
As underscore said, all component features (except entity and item hovers) are possible with MiniMessage (the latter is implemented by me via the item link placeholders).

If you want a way to break up formats into pieces so you can share parts of them between formats, or just so you can view them easier, there is the (custom) placeholder feature.

https://github.com/Hexaoxide/Carbon/blob/9beb9f839772ac19c20497e21a664d26cf025ad8/src/main/resources/config.yml#L96-L100

It's not exactly the same but it's somewhat close to what you want.

**Comment by Laarryy** [comment]
Closing as being able to use custom placeholders within custom placeholders within custom placeholders (as long as you order them correctly, as Vic has above) then you can effectively achieve this, making your format more like `<hover><name><message>` and less like a million lines long
