### ISSUE TITLE
[Feature] Permission to hide identity

### ISSUE THREAD

**Issue by Draycia** [Hexaoxide/Carbon#102]
With 1.16.4 coming, (vanilla) clients will have the ability to block/ignore users by UUID.
This requires messages to have an identity set.

However, some staff / servers may not be happy with players ignoring their staff and the headaches that may cause.
Proposal is to allow staff to set their messages' identity to `Identity.nil()` so that they cannot be ignored.

**Comment by Proximyst** [comment]
I'd like to propose a command such as `/bypassignores` to toggle such chat.

**Comment by Draycia** [comment]
0bb0bcc

@Proximyst maybe in the future, 1.1, 1.2
