### ISSUE TITLE
ending formatting used in prefixes?

### ISSUE THREAD

**Issue by Aitnys** [Hexaoxide/Carbon#117]
![image](https://user-images.githubusercontent.com/60077198/100276937-a1a24980-2f62-11eb-81ef-7f28f52e1a6e.png)

I've formatted the prefixes to be how they look after [SS] (command spy from essentials), I have ended each prefix with &r to make sure they don't bleed over to the next. But in CarbonChat this does not seem to have any effect? (as seen by the bottom part of the screenshot). When I use bold in a prefix it also bleeds on. 
Using a different color (the way you normally can cancel obfuscated or bold text) doesn't cancel out the format either. 

Am I missing something or is this a bug?

**Comment by Laarryy** [comment]
Try using <br> or <reset>

**Comment by Aitnys** [comment]
in the luckperms prefix? then this happens

![image](https://user-images.githubusercontent.com/60077198/100278785-b2a08a00-2f65-11eb-9a86-64ae9f060eb2.png)

**Comment by Laarryy** [comment]
@Aitnys no, in the chat format, after the prefix placeholder

**Comment by Aitnys** [comment]
then in the first example the MOD is still obfuscated.. but i can break down the luckperms prefix to all the separate elements i guess? trying that now.

**Comment by Aitnys** [comment]
i went from <displayname> to `%luckperms_prefix_element_highest_on_track_ranks%</obfuscated>%luckperms_prefix_element_highest_on_track_staff%</bold>%luckperms_prefix_element_highest_on_track_donor%%luckperms_prefix_element_highest_own% %player_name% %luckperms_suffix_element_highest_inherited%%luckperms_suffix_element_highest_on_track_stars%<reset>`

but it worked thanks!

**Comment by Laarryy** [comment]
you could just use %luckperms_prefix%<reset> - it will do the same and stacking logic will apply

**Comment by Aitnys** [comment]
nah because it still bleeds through to the second prefix :) 

![image](https://user-images.githubusercontent.com/60077198/100279901-a74e5e00-2f67-11eb-8077-46439c684616.png)

**Comment by Laarryy** [comment]
This is likely a bug - could you send your LP and Carbon configs please? perhaps in https://bytebin.lucko.me - does &r added to the end of each prefix not work?

**Comment by Aitnys** [comment]
CarbotChat: https://paste.dedimc.io/tasiguzafe.coffeescript
LuckPerms: https://paste.dedimc.io/hececewoxe.shell

and a pic of the actual prefix: (its green because i removed the <reset> again)
![image](https://user-images.githubusercontent.com/60077198/100280326-4e32fa00-2f68-11eb-837a-cc06ed8d7e9c.png)

**Comment by Laarryy** [comment]
and a pic of what chat looks like with exactly those settings?

**Comment by Aitnys** [comment]
right now its exactly how i want it... sorry i missunderstood what you wanted :) i can change things back to how it was when it was bleeding through give me a minute

**Comment by Laarryy** [comment]
oh no worries! yeah the buggy part is usually the part that needs fixing haha

**Comment by Aitnys** [comment]
https://paste.dedimc.io/qeburidosu.coffeescript

![image](https://user-images.githubusercontent.com/60077198/100281600-84717900-2f6a-11eb-9cac-9cd33dda0355.png)

it doesnt happen with `<displayname>` it only happens when i seperate it into the prefix, name suffix that it bleeds... (i wanted to add the space in that shows on other places but not here.. but turns out i was just blind before when i was looking where that space came from in other places :/ ) 

anyway i still think its a bug to have one placeholder bleed onto the next when theres a &r in there?

**Comment by Laarryy** [comment]
Can you confirm that this still happens on latest? `<reset>` should no longer appear when you replace &r with it

**Comment by Aitnys** [comment]
I am a bit confused? the `<reset>` showing up is in different places like tab, not where carbonchat controls it. 

But the bleeding it was doing from one placeholder to the next when &r is present seems to be fixed. Thanks!
