### ISSUE TITLE
[Feature] Nation Channel Context

### ISSUE THREAD

**Issue by partydev** [Hexaoxide/Carbon#127]
### Proposed Feature Description:
Towny towns are a context option for channels, please add Towny nations context so we can add nation channels.

### Proposed Feature Functionality:
Exact same as town context but with nations.

**Comment by Draycia** [comment]
Closing, 2.0.0 will not be using contexts. A new system will be implemented and the features it will support will be revisited at a later date.

Towny support will 100% be a feature at a later date, a new issue will be created regarding it when the time comes.
