### ISSUE TITLE
[Feature] Placeholder Registry API

### ISSUE THREAD

**Issue by broccolai** [Hexaoxide/Carbon#133]
### Proposed Feature Description:
The ability to register placeholder components to be replaced when sending a message.

### Proposed Feature Functionality:
This feature would work by an external plugin registering a new placeholder component with CarbonChat and then Carbon using it where applicable. Akin to PAPI but with Adventure Components

**Comment by Draycia** [comment]
bet

**Comment by broccolai** [comment]
oh i bet
