### ISSUE TITLE
[Feature] Permissions for format codes!

### ISSUE THREAD

**Issue by SrBedrock** [Hexaoxide/Carbon#28]
Currently there is only one permission (`carbonchat.formatting`) that allows the use of colors and formats, this is bad because it turns the chat into chaos when using formats like `&k` and etc.

My suggestion is to create a permission for colors and another for formats.

**Comment by MiniDigger** [comment]
https://github.com/KyoriPowered/adventure-text-minimessage/pull/50 will make this happen in minimessage:

![https://i.imgur.com/1LU95ug.png](https://i.imgur.com/1LU95ug.png)

this obviously doesn't support legacy stuff, no idea how you would handle that

**Comment by Draycia** [comment]
In 1.0.0 and 2.0.0 all non-minimessage colours and formats are converted over as MiniMessage tags prior to parsing.
In 2.0.0 some control will be given to admins and to users as to which tags they may use.
For admins, this will likely be a per-channel config option.
For users, this will be a permission.
