### ISSUE TITLE
[Feature] Command to blocks receiving private messages

### ISSUE THREAD

**Issue by SrBedrock** [Hexaoxide/Carbon#37]
### Suggestion

- Add command to not receive private messages.
- Add permission to be able to send private messages to players who have private messages blocked.

#### Exemple:

Command: `/msgtoggle` - Blocks receiving all private messages.
Permission: `carbonchat.msgtoggle` - Allows access to the `/msgtoggle` command

Permission: `carbonchat.msgtoggle.bypass` - Allows to send private messages to users that have disabled them with `/msgtoggle`.

**Comment by Draycia** [comment]
3b67e29 8b182cc will be a thing at 1.0 release
