### ISSUE TITLE
[Bug] Channel unavailable when being toggle

### ISSUE THREAD

**Issue by SrBedrock** [Hexaoxide/Carbon#38]
### Description

Channel unavailable when being toggle, returns the message `cannot-use-channel: 'You cannot use that channel!'`

Use `/toggle <channel>` and then try to use the command again.

The channel appears in the list of unavailable channels when using the `/chlist` command.

**Comment by Draycia** [comment]
ad857e326a57b7aabcd83d029306e6fca9f4c33b should fix it (build 90)

**Comment by SrBedrock** [comment]
Problem solved!
