### ISSUE TITLE
CC-Moderation replacements should support MiniMessage etc

### ISSUE THREAD

**Issue by ryantheleach** [Hexaoxide/Carbon#42]
Traditionally I had censored words colored so that people savvy would have a better idea that something was censored.

Also would allow people to use the obfuscate format option, which tends to be popular for censors.

**Comment by Draycia** [comment]
Might be difficult to do currently, as I use the `<pre><message></pre>` system to prevent unauthorized players from using formatting in their messages, which would also prevent filters from inserting formatting.

There is one way of addressing this but it produces some interesting results.
I'll keep this open in the meantime while I consider proper ways to make this possible.

**Comment by Draycia** [comment]
Follow-up, if https://github.com/KyoriPowered/adventure-text-minimessage/issues/45 is resolved this will likely be notably easier, as I'll be able to escape the player's message and then do the filtering / replacing.

**Comment by MiniDigger** [comment]
just fyi https://github.com/KyoriPowered/adventure-text-minimessage/issues/45 will be fixed with the rewrite (testable on the bye-bye-regex branch).
