### ISSUE TITLE
[Feature] Whisper Contexts

### ISSUE THREAD

**Issue by Laarryy** [Hexaoxide/Carbon#95]
### Proposed Feature Description:

The ability to use contexts with whispers and/or whisper channels

### Proposed Feature Functionality:

- Being able to whisper with someone only if within 100 blocks of them, etc.

**Comment by Laarryy** [comment]
Test

**Comment by Draycia** [comment]
Closing, 2.0.0 will not be using contexts. A new system will be implemented and the features it will support will be revisited at a later date.
